name: Python application

# This workflow lints, type-checks, tests, and builds the AzanSchedular Python app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Type check with mypy
      run: |
        pip install mypy
        python -m pip install types-python-dateutil types-aiofiles types-requests types-tabulate
        mypy AzanSchedular

    - name: Run tests
      run: |
        pip install pytest pytest-asyncio httpx
        pytest

    - name: Build Azan Scheduler EXE
      run: |
        pip install pyinstaller
        pyinstaller AzanSchedular.spec
        mkdir ..\dist
        move dist\AzanSchedular.exe ..\dist\AzanSchedular.exe
