name: Python application

# This workflow lints, type-checks, tests, and builds the AzanSchedular Python app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Type check with mypy
      run: |
        pip install mypy
        python -m pip install types-python-dateutil types-aiofiles types-requests types-tabulate
        mypy AzanSchedular

    - name: Run tests
      run: |
        pip install pytest pytest-asyncio httpx
        pytest

    - name: Build Azan Scheduler EXE
      run: |
        pip install pyinstaller
        pyinstaller AzanSchedular.spec
        if not exist dist mkdir dist
        copy dist\AzanSchedular.exe dist\AzanSchedular.exe

    - name: Upload EXE as workflow artifact
      uses: actions/upload-artifact@v4
      with:
        name: AzanSchedular-exe
        path: dist/AzanSchedular.exe

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1
      id: create_release
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload EXE to Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/AzanSchedular.exe
        asset_name: AzanSchedular.exe
        asset_content_type: application/vnd.microsoft.portable-executable
